// Generated by `just gen-copy` from copy/errors.toml. Do not edit.

export type ErrorWeight = 'urgent' | 'neutral'

export type ErrorCopyEntry = {
  weight: ErrorWeight
  de: { title: string; action: string }
  fr: { title: string; action: string }
  it: { title: string; action: string }
  en: { title: string; action: string }
}

export const errorCopy = {
  'SZ-E101': {
    weight: 'urgent',
    de: { title: 'E-Mail oder Passwort stimmt nicht.', action: 'Probier es nochmal. Wenn du das Passwort vergessen hast, setz es auf deinem Server zurück.' },
    fr: { title: 'L\'e-mail ou le mot de passe est incorrect.', action: 'Réessaie. Si tu as oublié ton mot de passe, réinitialise-le sur ton serveur.' },
    it: { title: 'L\'e-mail o la password non è corretta.', action: 'Riprova. Se hai dimenticato la password, reimpostala sul tuo server.' },
    en: { title: 'That email or password is wrong.', action: 'Try again. If you forgot your password, reset it on your server.' },
  },
  'SZ-E102': {
    weight: 'neutral',
    de: { title: 'Du bist nicht angemeldet.', action: 'Melde dich nochmal an.' },
    fr: { title: 'Tu n\'es pas connecté.', action: 'Reconnecte-toi.' },
    it: { title: 'Non hai effettuato l\'accesso.', action: 'Accedi di nuovo.' },
    en: { title: 'You\'re not signed in.', action: 'Sign in again.' },
  },
  'SZ-E103': {
    weight: 'neutral',
    de: { title: 'Deine Sitzung ist abgelaufen.', action: 'Melde dich nochmal an, dann geht es weiter.' },
    fr: { title: 'Ta session a expiré.', action: 'Reconnecte-toi pour continuer.' },
    it: { title: 'La sessione è scaduta.', action: 'Accedi di nuovo per continuare.' },
    en: { title: 'Your session ran out.', action: 'Sign in again to carry on.' },
  },
  'SZ-E104': {
    weight: 'neutral',
    de: { title: 'Dieser Server nimmt keine neuen Konten an.', action: 'Frag die Person, die den Server betreibt, um eine Einladung.' },
    fr: { title: 'Ce serveur n\'accepte pas de nouveaux comptes.', action: 'Demande une invitation à la personne qui gère le serveur.' },
    it: { title: 'Questo server non accetta nuovi account.', action: 'Chiedi un invito a chi gestisce il server.' },
    en: { title: 'This server isn\'t taking new accounts.', action: 'Ask whoever runs the server for an invite.' },
  },
  'SZ-E105': {
    weight: 'urgent',
    de: { title: 'Für diese E-Mail gibt es schon ein Konto.', action: 'Melde dich damit an oder nimm eine andere Adresse.' },
    fr: { title: 'Un compte existe déjà avec cet e-mail.', action: 'Connecte-toi avec, ou utilise une autre adresse.' },
    it: { title: 'Esiste già un account con questa e-mail.', action: 'Accedi con quello o usa un altro indirizzo.' },
    en: { title: 'That email already has an account.', action: 'Sign in with it, or use another address.' },
  },
  'SZ-E201': {
    weight: 'neutral',
    de: { title: 'Das gibt es hier nicht.', action: 'Geh zurück und probier es nochmal.' },
    fr: { title: 'Cela n\'existe pas ici.', action: 'Reviens en arrière et réessaie.' },
    it: { title: 'Qui non c\'è nulla.', action: 'Torna indietro e riprova.' },
    en: { title: 'That isn\'t here.', action: 'Go back and try again.' },
  },
  'SZ-E202': {
    weight: 'neutral',
    de: { title: 'Dieses Kind ist nicht mehr auf dem Server.', action: 'Geh zurück zur Übersicht.' },
    fr: { title: 'Cet enfant n\'est plus sur le serveur.', action: 'Retourne à la vue d\'ensemble.' },
    it: { title: 'Questo bambino non è più sul server.', action: 'Torna alla panoramica.' },
    en: { title: 'That child isn\'t on the server any more.', action: 'Go back to the overview.' },
  },
  'SZ-E301': {
    weight: 'urgent',
    de: { title: 'Der Server konnte damit nichts anfangen.', action: 'Prüf deine Eingaben und schick es nochmal.' },
    fr: { title: 'Le serveur n\'a pas pu traiter cette demande.', action: 'Vérifie ce que tu as saisi et renvoie.' },
    it: { title: 'Il server non ha potuto usare questi dati.', action: 'Controlla quello che hai inserito e riprova.' },
    en: { title: 'The server couldn\'t use that.', action: 'Check what you entered and send it again.' },
  },
  'SZ-E304': {
    weight: 'neutral',
    de: { title: 'Zu viele Versuche kurz nacheinander.', action: 'Warte einen Moment und probier es nochmal.' },
    fr: { title: 'Trop de tentatives d\'affilée.', action: 'Attends un instant et réessaie.' },
    it: { title: 'Troppi tentativi ravvicinati.', action: 'Aspetta un momento e riprova.' },
    en: { title: 'Too many tries in a row.', action: 'Wait a moment and try again.' },
  },
  'SZ-E501': {
    weight: 'neutral',
    de: { title: 'Keine Verbindung.', action: 'Prüf dein WLAN oder das mobile Netz und probier es nochmal.' },
    fr: { title: 'Pas de connexion.', action: 'Vérifie le Wi-Fi ou les données mobiles, puis réessaie.' },
    it: { title: 'Nessuna connessione.', action: 'Controlla il Wi-Fi o i dati mobili e riprova.' },
    en: { title: 'No connection.', action: 'Check your Wi-Fi or mobile data, then try again.' },
  },
  'SZ-E502': {
    weight: 'neutral',
    de: { title: 'Der Server hat zu lange gebraucht.', action: 'Probier es gleich nochmal.' },
    fr: { title: 'Le serveur a mis trop de temps.', action: 'Réessaie dans un instant.' },
    it: { title: 'Il server ha impiegato troppo tempo.', action: 'Riprova tra poco.' },
    en: { title: 'The server took too long.', action: 'Try again in a moment.' },
  },
  'SZ-E503': {
    weight: 'urgent',
    de: { title: 'Die sichere Verbindung ist fehlgeschlagen.', action: 'Prüf die Serveradresse und das Zertifikat deines Servers.' },
    fr: { title: 'La connexion sécurisée a échoué.', action: 'Vérifie l\'adresse du serveur et son certificat.' },
    it: { title: 'La connessione sicura non è riuscita.', action: 'Controlla l\'indirizzo del server e il suo certificato.' },
    en: { title: 'The secure connection failed.', action: 'Check the server address and your server\'s certificate.' },
  },
  'SZ-E504': {
    weight: 'urgent',
    de: { title: 'Die Antwort kam nicht von deinem Server.', action: 'Oft steckt ein Gast-WLAN mit Anmeldeseite dahinter. Melde dich dort an und probier es nochmal.' },
    fr: { title: 'La réponse ne venait pas de ton serveur.', action: 'Souvent c\'est un Wi-Fi public avec une page de connexion. Connecte-toi, puis réessaie.' },
    it: { title: 'La risposta non arrivava dal tuo server.', action: 'Spesso c\'è di mezzo un Wi-Fi pubblico con pagina di accesso. Accedi e riprova.' },
    en: { title: 'That answer didn\'t come from your server.', action: 'Often it\'s a guest Wi-Fi with a login page. Sign in there, then try again.' },
  },
  'SZ-E505': {
    weight: 'urgent',
    de: { title: 'Der Server ist unter dieser Adresse nicht erreichbar.', action: 'Prüf die Adresse und ob der Server läuft.' },
    fr: { title: 'Le serveur est injoignable à cette adresse.', action: 'Vérifie l\'adresse et que le serveur tourne.' },
    it: { title: 'Il server non è raggiungibile a questo indirizzo.', action: 'Controlla l\'indirizzo e che il server sia in funzione.' },
    en: { title: 'The server can\'t be reached at that address.', action: 'Check the address, and that the server is running.' },
  },
  'SZ-E703': {
    weight: 'urgent',
    de: { title: 'Gespeicherte Daten auf diesem Gerät konnten nicht gelesen werden.', action: 'Probier es nochmal. Bleibt es so, meld dich ab und wieder an.' },
    fr: { title: 'Des données enregistrées sur cet appareil n\'ont pas pu être lues.', action: 'Réessaie. Si cela persiste, déconnecte-toi puis reconnecte-toi.' },
    it: { title: 'Non è stato possibile leggere i dati salvati su questo dispositivo.', action: 'Riprova. Se continua, esci e accedi di nuovo.' },
    en: { title: 'Saved data on this device couldn\'t be read.', action: 'Try again. If it keeps happening, sign out and back in.' },
  },
  'SZ-E707': {
    weight: 'urgent',
    de: { title: 'Etwas ist unerwartet schiefgelaufen.', action: 'Lade die Seite neu. Passiert es wieder, schick uns den Code und die Referenz unten.' },
    fr: { title: 'Quelque chose s\'est mal passé de façon inattendue.', action: 'Recharge la page. Si cela se reproduit, envoie-nous le code et la référence ci-dessous.' },
    it: { title: 'Qualcosa è andato storto in modo inatteso.', action: 'Ricarica la pagina. Se succede di nuovo, mandaci il codice e il riferimento qui sotto.' },
    en: { title: 'Something went wrong unexpectedly.', action: 'Reload the page. If it happens again, send us the code and reference below.' },
  },
  'SZ-E901': {
    weight: 'urgent',
    de: { title: 'Auf dem Server ist etwas schiefgelaufen.', action: 'Probier es gleich nochmal. Bleibt es so, such im Server-Log nach der Referenz unten.' },
    fr: { title: 'Un problème est survenu côté serveur.', action: 'Réessaie dans un instant. Si cela persiste, cherche la référence ci-dessous dans le journal du serveur.' },
    it: { title: 'Sul server è andato storto qualcosa.', action: 'Riprova tra poco. Se continua, cerca il riferimento qui sotto nel log del server.' },
    en: { title: 'Something went wrong on the server.', action: 'Try again in a moment. If it keeps happening, look for the reference below in the server log.' },
  },
  'SZ-E902': {
    weight: 'urgent',
    de: { title: 'Der Server erreicht seine Datenbank nicht.', action: 'Probier es später nochmal. Prüf, ob die Datenbank läuft.' },
    fr: { title: 'Le serveur n\'atteint pas sa base de données.', action: 'Réessaie plus tard. Vérifie que la base de données tourne.' },
    it: { title: 'Il server non raggiunge il suo database.', action: 'Riprova più tardi. Controlla che il database sia in funzione.' },
    en: { title: 'The server can\'t reach its database.', action: 'Try again later. Check that the database is running.' },
  },
} as const satisfies Record<string, ErrorCopyEntry>

export type ErrorCopyCode = keyof typeof errorCopy
