/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["soft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["purge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol the phone the parent is holding, without a pairing code.
         * @description This is what makes one app work for both roles: a parent signs in on the
         *     child's phone, picks the child, and the app trades that session for a device
         *     token — then deletes the session, so no parent credentials and no parent
         *     session stay behind on a child's phone. Codes remain for the case where the
         *     parent is not there to sign in.
         */
        post: operations["claim_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mint_enrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChildResponse: {
            display_name: string;
            /** Format: uuid */
            id: string;
        };
        ClaimDevice: {
            label: string;
            model: string;
            platform: string;
        };
        ClaimedDeviceResponse: {
            /** Format: uuid */
            device_id: string;
            /** @description Long-lived, write-only. Shown once; only its hash is stored. */
            token: string;
        };
        Credentials: {
            email: string;
            password: string;
        };
        DeviceResponse: {
            /** Format: uuid */
            child_id: string;
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            model: string;
            platform: string;
            revoked: boolean;
            stale: boolean;
        };
        DeviceStatus: {
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            stale: boolean;
        };
        DeviceTotal: {
            /** Format: int64 */
            screen_on_ms: number;
            start: string;
            /** Format: int32 */
            unlock_count: number;
        };
        EnrollRequest: {
            code: string;
            label: string;
            model: string;
            platform: string;
        };
        EnrolledResponse: {
            /** Format: uuid */
            device_id: string;
            /** @description Long-lived, write-only. Shown once; only its hash is stored. */
            token: string;
        };
        EnrollmentResponse: {
            code: string;
            /** Format: date-time */
            expires_at: string;
            qr_payload: string;
        };
        IngestApp: {
            /** Format: int64 */
            foreground_ms: number;
            label: string;
            /** Format: int32 */
            launch_count: number;
            package: string;
        };
        IngestHour: {
            apps: components["schemas"]["IngestApp"][];
            /** Format: date-time */
            computed_at: string;
            /** Format: date-time */
            hour_start: string;
            /** Format: int64 */
            screen_on_ms: number;
            tz: string;
            /** Format: int32 */
            unlock_count: number;
        };
        IngestRequest: {
            /** Format: date-time */
            device_time: string;
            hours: components["schemas"]["IngestHour"][];
            /** Format: int32 */
            schema: number;
        };
        IngestResponse: {
            accepted: string[];
            rejected: components["schemas"]["Rejected"][];
        };
        MeResponse: {
            email: string;
            /** Format: uuid */
            family_id: string;
            /** Format: uuid */
            id: string;
        };
        NewChild: {
            display_name: string;
        };
        Point: {
            /** Format: int64 */
            foreground_ms: number;
            /** Format: int32 */
            launch_count: number;
            /** @description RFC3339 instant for hourly buckets, `YYYY-MM-DD` for daily ones. */
            start: string;
        };
        /**
         * @description Deletes for real and reports what went, so "delete my child's data" is
         *     verifiable rather than a promise.
         */
        PurgeResponse: {
            /** Format: int64 */
            deleted_device_hours: number;
            /** Format: int64 */
            deleted_usage_days: number;
            /** Format: int64 */
            deleted_usage_hours: number;
        };
        RegisteredResponse: {
            /** Format: uuid */
            family_id: string;
        };
        Rejected: {
            /** Format: date-time */
            hour_start: string;
            permanent: boolean;
            reason: string;
        };
        Series: {
            label: string;
            package: string;
            points: components["schemas"]["Point"][];
        };
        SummaryResponse: {
            /** Format: uuid */
            child_id: string;
            /** Format: date */
            date: string;
            first_activity?: string | null;
            last_activity?: string | null;
            top_apps: components["schemas"]["TopApp"][];
            /** Format: int64 */
            total_ms: number;
            tz: string;
            /** Format: int64 */
            unlock_count: number;
        };
        TopApp: {
            /** Format: int64 */
            foreground_ms: number;
            label: string;
            package: string;
        };
        UsageResponse: {
            bucket: string;
            /** Format: uuid */
            child_id: string;
            device_totals: components["schemas"]["DeviceTotal"][];
            devices: components["schemas"]["DeviceStatus"][];
            /** Format: date */
            from: string;
            series: components["schemas"]["Series"][];
            /** Format: date */
            to: string;
            tz: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Session cookie issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts from this IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Family and first parent created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredResponse"];
                };
            };
            /** @description Registration disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password too short */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Children in this family */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewChild"];
            };
        };
        responses: {
            /** @description Child created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty display name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    soft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    purge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows actually deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimDevice"];
            };
        };
        responses: {
            /** @description Device enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedDeviceResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty platform, model or label */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mint_enrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time enrollment code */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary: {
        parameters: {
            query: {
                date: string;
                tz: string;
            };
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One local day, summarised */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usage: {
        parameters: {
            query: {
                from: string;
                to: string;
                bucket?: string;
                tz: string;
            };
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage series for the requested local dates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices in this family */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such device in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Device enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrolledResponse"];
                };
            };
            /** @description Unknown, expired or already-used code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Per-row accept/reject result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Unsupported schema version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or revoked device token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many hours in one batch */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device rate limit */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in parent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
