/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hides the child and stops their phones, in one transaction.
         * @description The row itself survives — historical usage stays attributable, and the
         *     dedicated `DELETE /v1/children/{id}/data` is what actually erases figures,
         *     deliberately separate so "delete my child's data" is its own reported act.
         *
         *     Revoking the devices is not tidying-up: `Device` authorizes on
         *     `devices.revoked_at` alone, so without this a phone whose child is gone from
         *     every parent screen keeps uploading hours that nothing can read back. A
         *     parent removing a child means "and stop reporting".
         */
        delete: operations["soft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["purge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol the phone the parent is holding, without a pairing code.
         * @description This is what makes one app work for both roles: a parent signs in on the
         *     child's phone, picks the child, and the app trades that session for a device
         *     token — then deletes the session, so no parent credentials and no parent
         *     session stay behind on a child's phone. Codes remain for the case where the
         *     parent is not there to sign in.
         */
        post: operations["claim_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mint_enrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["insight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/children/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The one read a device token buys, and it takes no id: a device sees the child
         *     it was enrolled for and has no way to name another. `/v1/children` and every
         *     other parent route still refuse a device token — there is a test for it.
         */
        get: operations["my_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One app, in both weeks. `ms` may be lower than `previous_ms`; a mover moves
         *     in either direction and the renderer says which.
         */
        AppMove: {
            /** Format: int64 */
            foreground_ms: number;
            label: string;
            package: string;
            /** Format: int64 */
            previous_foreground_ms: number;
        };
        ChildResponse: {
            display_name: string;
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Foreground milliseconds so far in the caller's local today. Zero, never
             *     null: a quiet day is a real number and an absent one renders as a hole.
             */
            today_ms: number;
        };
        ClaimDevice: {
            label: string;
            model: string;
            platform: string;
        };
        ClaimedDeviceResponse: {
            /** Format: uuid */
            device_id: string;
            /** @description Long-lived, write-only. Shown once; only its hash is stored. */
            token: string;
        };
        Credentials: {
            email: string;
            password: string;
        };
        DeviceResponse: {
            /** Format: uuid */
            child_id: string;
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            model: string;
            platform: string;
            revoked: boolean;
            stale: boolean;
        };
        DeviceStatus: {
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            stale: boolean;
        };
        DeviceTotal: {
            /**
             * @description False means none of the devices reporting this bucket could observe
             *     background playback — not that nothing played. Rendering the two alike
             *     is the silent zero this product exists not to tell.
             */
            background_measured: boolean;
            /** Format: int64 */
            screen_on_ms: number;
            /**
             * @description RFC3339 instant for hourly buckets, `YYYY-MM-DD` for daily ones — same
             *     dual format as `Point.start`, and the exact field a wrong `bucket` on
             *     the client side answers wrong for (`crates/core/src/selfusage.rs`).
             */
            start: string;
            /** Format: int32 */
            unlock_count: number;
        };
        EnrollRequest: {
            code: string;
            label: string;
            model: string;
            platform: string;
        };
        EnrolledResponse: {
            /** Format: uuid */
            device_id: string;
            /** @description Long-lived, write-only. Shown once; only its hash is stored. */
            token: string;
        };
        EnrollmentResponse: {
            code: string;
            /** Format: date-time */
            expires_at: string;
            qr?: null | components["schemas"]["QrCode"];
            qr_payload: string;
        };
        /** @enum {string} */
        ErrorCode: "SZ-E101" | "SZ-E102" | "SZ-E103" | "SZ-E104" | "SZ-E105" | "SZ-E106" | "SZ-E201" | "SZ-E202" | "SZ-E203" | "SZ-E204" | "SZ-E205" | "SZ-E301" | "SZ-E302" | "SZ-E303" | "SZ-E304" | "SZ-E501" | "SZ-E502" | "SZ-E503" | "SZ-E504" | "SZ-E505" | "SZ-E506" | "SZ-E601" | "SZ-E602" | "SZ-E603" | "SZ-E604" | "SZ-E605" | "SZ-E701" | "SZ-E702" | "SZ-E703" | "SZ-E704" | "SZ-E705" | "SZ-E706" | "SZ-E707" | "SZ-E901" | "SZ-E902";
        IngestApp: {
            /**
             * Format: int64
             * @description Media playing with the screen off. Separate from `foreground_ms` in
             *     every consumer; never add the two together.
             */
            background_ms?: number;
            /** Format: int64 */
            foreground_ms: number;
            label: string;
            /** Format: int32 */
            launch_count: number;
            package: string;
        };
        IngestHour: {
            apps: components["schemas"]["IngestApp"][];
            /**
             * @description Whether this device could observe background playback at all for this
             *     hour. `false` is NOT "nothing played" — it is "we do not know": an
             *     iPhone, or an Android phone whose family declined the grant.
             */
            background_measured?: boolean;
            /** Format: date-time */
            computed_at: string;
            /** Format: date-time */
            hour_start: string;
            /** Format: int64 */
            screen_on_ms: number;
            tz: string;
            /** Format: int32 */
            unlock_count: number;
        };
        IngestRequest: {
            /** Format: date-time */
            device_time: string;
            hours: components["schemas"]["IngestHour"][];
            /** Format: int32 */
            schema: number;
        };
        IngestResponse: {
            accepted: string[];
            rejected: components["schemas"]["Rejected"][];
        };
        InsightResponse: {
            /** Format: uuid */
            child_id: string;
            tz: string;
            week: components["schemas"]["WeekComparison"];
        };
        MeResponse: {
            email: string;
            /** Format: uuid */
            family_id: string;
            /** Format: uuid */
            id: string;
        };
        NewChild: {
            display_name: string;
        };
        Point: {
            /**
             * Format: int64
             * @description Media playing with the screen off. A separate measure: never add it to
             *     `foreground_ms`, on any surface.
             */
            background_ms: number;
            /** Format: int64 */
            foreground_ms: number;
            /** Format: int32 */
            launch_count: number;
            /** @description RFC3339 instant for hourly buckets, `YYYY-MM-DD` for daily ones. */
            start: string;
        };
        /**
         * @description The body of every error response.
         *
         *     `detail` is for the log and the copy-details block a parent can send. It is
         *     never rendered as the message a parent reads: it is English, and the app
         *     speaks four languages. The client looks the copy up by `code`.
         */
        Problem: {
            code: components["schemas"]["ErrorCode"];
            detail: string;
            /**
             * @description Six hex characters, the head of the request id. Filled in by the
             *     normalise layer, which is the only place with access to the request.
             */
            ref: string;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        /**
         * @description Deletes for real and reports what went, so "delete my child's data" is
         *     verifiable rather than a promise.
         */
        PurgeResponse: {
            /** Format: int64 */
            deleted_device_hours: number;
            /** Format: int64 */
            deleted_usage_days: number;
            /** Format: int64 */
            deleted_usage_hours: number;
        };
        /**
         * @description A square of modules, row by row, `1` dark and `0` light — the quiet zone
         *     included, so `size` is what a renderer draws and nothing more is needed.
         *
         *     Characters rather than booleans: this crosses the API as JSON, where 33
         *     rows of `"1011…"` stay readable in a response a self-hoster is debugging,
         *     and an array of 1681 booleans does not.
         */
        QrCode: {
            /** @description `size` strings of `size` characters each. */
            rows: string[];
            /**
             * Format: int32
             * @description Modules per side, quiet zone included.
             */
            size: number;
        };
        RegisteredResponse: {
            /** Format: uuid */
            family_id: string;
        };
        Rejected: {
            /** Format: date-time */
            hour_start: string;
            permanent: boolean;
            reason: string;
        };
        Series: {
            label: string;
            package: string;
            points: components["schemas"]["Point"][];
        };
        UsageResponse: {
            bucket: string;
            /** Format: uuid */
            child_id: string;
            device_totals: components["schemas"]["DeviceTotal"][];
            devices: components["schemas"]["DeviceStatus"][];
            /** Format: date */
            from: string;
            series: components["schemas"]["Series"][];
            /** Format: date */
            to: string;
            tz: string;
        };
        WaitlistRequest: {
            email: string;
            /** @description One of `de`, `fr`, `it`, `en`. */
            locale: string;
        };
        /** @description Seven days against the seven before them. */
        WeekComparison: {
            /**
             * Format: int32
             * @description Shipped rather than assumed, so a renderer can name the hour it is
             *     talking about instead of hard-coding a 21 of its own.
             */
            evening_from_hour: number;
            /**
             * Format: int64
             * @description Screen time from `evening_from_hour` to local midnight, a subset of
             *     `total_ms` and never something to add to it.
             */
            evening_ms: number;
            /**
             * Format: date
             * @description First and last local day of the recent week, both inclusive.
             */
            from: string;
            /** @description Ranked by distance moved, longest first, at most [`MAX_MOVERS`]. */
            movers: components["schemas"]["AppMove"][];
            /** Format: int64 */
            previous_evening_ms: number;
            /**
             * Format: date
             * @description The week before, both inclusive.
             */
            previous_from: string;
            /**
             * @description False when no device reported anything in the earlier week. A week
             *     against nothing is not a doubling, it is a first week, and every
             *     surface has to say so rather than print a percentage.
             */
            previous_measured: boolean;
            /** Format: date */
            previous_to: string;
            /** Format: int64 */
            previous_total_ms: number;
            /** Format: date */
            to: string;
            /** Format: int64 */
            total_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Session cookie issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts from this IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Family and first parent created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredResponse"];
                };
            };
            /** @description Registration disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password too short */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query: {
                tz: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Children in this family */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewChild"];
            };
        };
        responses: {
            /** @description Child created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty display name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    soft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hidden, and its devices revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    purge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows actually deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimDevice"];
            };
        };
        responses: {
            /** @description Device enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedDeviceResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty platform, model or label */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mint_enrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time enrollment code */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    insight: {
        parameters: {
            query: {
                /**
                 * @description The local date the parent is looking at. Today is part of neither week
                 *     — the comparison ends yesterday — but it decides where the two weeks
                 *     fall, and only the client knows which day it is where the family lives.
                 */
                date: string;
                tz: string;
            };
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The last full week against the one before it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usage: {
        parameters: {
            query: {
                from: string;
                to: string;
                bucket?: string;
                tz: string;
            };
            header?: never;
            path: {
                /** @description Child id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage series for the requested local dates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description No such child in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices in this family */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such device in this family */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Device enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrolledResponse"];
                };
            };
            /** @description Unknown, expired or already-used code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Per-row accept/reject result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Unsupported schema version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or revoked device token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many hours in one batch */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device rate limit */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in parent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_usage: {
        parameters: {
            query: {
                from: string;
                to: string;
                bucket?: string;
                tz: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This device's own child, for the requested local dates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description Unknown or revoked device token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown timezone */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device read limit */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description On the list — also the answer when the address was already on it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an email address, or a language the site does not speak */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
