use crate::catalog::{Catalog, Surface, Weight};

const LOCALES: [&str; 4] = ["de", "fr", "it", "en"];

fn weight_str(weight: Weight) -> &'static str {
    match weight {
        Weight::Urgent => "urgent",
        Weight::Neutral => "neutral",
    }
}

/// One TypeScript module holding every locale, because the dashboard already
/// ships all four dictionaries and switches between them at runtime.
pub fn web(catalog: &Catalog) -> String {
    let mut out = String::from(
        "// Generated by `just gen-copy` from copy/errors.toml. Do not edit.\n\n\
         export type ErrorWeight = 'urgent' | 'neutral'\n\n\
         export type ErrorCopyEntry = {\n  weight: ErrorWeight\n  \
         de: { title: string; action: string }\n  \
         fr: { title: string; action: string }\n  \
         it: { title: string; action: string }\n  \
         en: { title: string; action: string }\n}\n\n\
         export const errorCopy = {\n",
    );
    for (code, entry) in &catalog.entries {
        if !entry.reach.contains(&Surface::Web) {
            continue;
        }
        out.push_str(&format!(
            "  '{code}': {{\n    weight: '{}',\n",
            weight_str(entry.weight)
        ));
        for locale in LOCALES {
            let copy = &entry.locales[locale];
            out.push_str(&format!(
                "    {locale}: {{ title: {}, action: {} }},\n",
                ts_string(&copy.title),
                ts_string(&copy.action)
            ));
        }
        out.push_str("  },\n");
    }
    out.push_str("} as const satisfies Record<string, ErrorCopyEntry>\n\n");
    out.push_str("export type ErrorCopyCode = keyof typeof errorCopy\n");
    out
}

/// One .strings per lproj, keyed `error.<code>.title` / `.action`.
pub fn ios(catalog: &Catalog, locale: &str) -> String {
    let mut out =
        String::from("/* Generated by `just gen-copy` from copy/errors.toml. Do not edit. */\n\n");
    for (code, entry) in &catalog.entries {
        if !entry.reach.contains(&Surface::Ios) {
            continue;
        }
        let copy = &entry.locales[locale];
        out.push_str(&format!(
            "\"error.{code}.title\" = \"{}\";\n\"error.{code}.action\" = \"{}\";\n",
            strings_escape(&copy.title),
            strings_escape(&copy.action)
        ));
    }
    out
}

/// Android resource names cannot contain a hyphen, so SZ-E501 becomes
/// error_SZ_E501_title.
pub fn android(catalog: &Catalog, locale: &str) -> String {
    let mut out = String::from(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <!-- Generated by `just gen-copy` from copy/errors.toml. Do not edit. -->\n\
         <resources>\n",
    );
    for (code, entry) in &catalog.entries {
        if !entry.reach.contains(&Surface::Android) {
            continue;
        }
        let name = code.replace('-', "_");
        let copy = &entry.locales[locale];
        out.push_str(&format!(
            "    <string name=\"error_{name}_title\">{}</string>\n    \
             <string name=\"error_{name}_action\">{}</string>\n",
            android_escape(&copy.title),
            android_escape(&copy.action)
        ));
    }
    out.push_str("</resources>\n");
    out
}

fn ts_string(value: &str) -> String {
    format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'"))
}

fn strings_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// `&` and `<` break the XML parse; a bare apostrophe breaks the Android
/// resource compiler specifically, and French copy is full of them.
fn android_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tiny() -> Catalog {
        toml::from_str(
            r#"
            [SZ-E501]
            weight = "neutral"
            reach = ["web", "ios", "android"]
            de = { title = "Keine Verbindung.", action = "Prüf dein WLAN." }
            fr = { title = "Pas de connexion.", action = "Vérifie ton Wi-Fi." }
            it = { title = "Nessuna connessione.", action = "Controlla il Wi-Fi." }
            en = { title = "No connection.", action = "Check your Wi-Fi." }

            [SZ-E603]
            weight = "neutral"
            reach = ["android"]
            de = { title = "Kein Zugriff.", action = "Schalte ihn ein." }
            fr = { title = "Pas d'accès.", action = "Active-le." }
            it = { title = "Nessun accesso.", action = "Attivalo." }
            en = { title = "No access.", action = "Switch it on." }
            "#,
        )
        .unwrap()
    }

    #[test]
    fn web_gets_only_the_codes_it_can_emit() {
        let out = web(&tiny());
        assert!(out.contains("'SZ-E501'"), "{out}");
        assert!(
            !out.contains("SZ-E603"),
            "web cannot emit an Android notification-access failure: {out}"
        );
    }

    #[test]
    fn web_carries_all_four_locales_and_the_weight() {
        let out = web(&tiny());
        for locale in ["de:", "fr:", "it:", "en:"] {
            assert!(out.contains(locale), "missing {locale} in {out}");
        }
        assert!(out.contains("weight: 'neutral'"), "{out}");
    }

    #[test]
    fn ios_escapes_quotes_and_keys_by_code() {
        let out = ios(&tiny(), "en");
        assert!(
            out.contains(r#""error.SZ-E501.title" = "No connection.";"#),
            "{out}"
        );
        assert!(
            out.contains(r#""error.SZ-E501.action" = "Check your Wi-Fi.";"#),
            "{out}"
        );
        assert!(!out.contains("SZ-E603"), "iOS cannot emit SZ-E603: {out}");
    }

    /// An unescaped apostrophe in French is a build error in Android resources,
    /// and an unescaped & is a parse error. Both appear in real copy.
    #[test]
    fn android_escapes_what_the_resource_parser_would_choke_on() {
        let out = android(&tiny(), "fr");
        assert!(out.contains(r"Pas d\'accès"), "{out}");
        assert!(out.contains(r#"name="error_SZ_E603_title""#), "{out}");
        assert!(
            !out.contains("SZ-E501\""),
            "codes use underscores in resource names: {out}"
        );
    }

    #[test]
    fn generated_files_say_they_are_generated() {
        assert!(web(&tiny()).starts_with("// Generated by `just gen-copy`"));
        assert!(ios(&tiny(), "de").starts_with("/* Generated by `just gen-copy`"));
        assert!(android(&tiny(), "de").contains("<!-- Generated by `just gen-copy`"));
    }
}
