import XCTest
@testable import SchirmziitKit

/// Without a `UILaunchScreen` key iOS runs the app in legacy compatibility mode:
/// it renders at an older screen size and letterboxes the result, so the app sits
/// between a black bar at the top and one at the bottom on every modern iPhone.
/// Nothing about the SwiftUI views says so, and no snapshot can catch it — the
/// bars are the window, not the layout.
///
/// The plists are generated by xcodegen from `ios/project.yml`, which `ios-check`
/// re-runs before this test, so reading the generated file checks the whole chain:
/// drop the key from `project.yml` and the file on disk loses it too.
final class LaunchScreenTests: XCTestCase {
    private func iosDirectory() -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()          // ios/Tests
            .deletingLastPathComponent()          // ios
    }

    func testTheAppDeclaresALaunchScreen() throws {
        let url = iosDirectory().appendingPathComponent("Sources/Resources/Info.plist")
        let info = try XCTUnwrap(NSDictionary(contentsOf: url) as? [String: Any],
                                 "no generated Info.plist at \(url.path)")
        XCTAssertNotNil(info["UILaunchScreen"] as? [String: Any],
                        "UILaunchScreen is missing — iOS letterboxes the app")
    }

    /// Both app targets share this one plist, so the fix cannot land on the real
    /// target and miss the free-team one a developer actually installs.
    func testBothAppTargetsShareThatPlist() throws {
        let url = iosDirectory().appendingPathComponent("project.yml")
        let yaml = try String(contentsOf: url, encoding: .utf8)
        let declarations = yaml.components(separatedBy: "path: Sources/Resources/Info.plist").count - 1
        XCTAssertEqual(declarations, 2,
                       "expected Schirmziit and SchirmziitLocal to share one Info.plist")
    }
}
